name: CI Principal
 
on:
  push:
    branches: [ "main" ]
 
jobs:
  test-api:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
 
  platform-ci:
    name: Build and Push Docker Image
    needs: test-api # Ce job attendra que les tests soient réussis pour se lancer
    # Utilisation de ton fork temporairement pour débloquer l'action
    uses: ju-stoe/platform-demo/.github/workflows/ci-ju-stoe.yml@add-ci-ju-stoe